
package webservices.gov.usgs.gisdata.xmlwebservices2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Elevation_ServiceSoap", targetNamespace = "http://gisdata.usgs.gov/XMLWebServices2/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ElevationServiceSoap {


    /**
     * Returns a value from a single elevation source for a given latitude/longitude point
     * 
     * @param elevationUnits
     * @param yValue
     * @param sourceLayer
     * @param xValue
     * @param elevationOnly
     * @return
     *     returns gov.usgs.gisdata.xmlwebservices2.GetElevationResponse.GetElevationResult
     */
    @WebMethod(action = "http://gisdata.usgs.gov/XMLWebServices2/getElevation")
    @WebResult(name = "getElevationResult", targetNamespace = "http://gisdata.usgs.gov/XMLWebServices2/")
    @RequestWrapper(localName = "getElevation", targetNamespace = "http://gisdata.usgs.gov/XMLWebServices2/", className = "gov.usgs.gisdata.xmlwebservices2.GetElevation")
    @ResponseWrapper(localName = "getElevationResponse", targetNamespace = "http://gisdata.usgs.gov/XMLWebServices2/", className = "gov.usgs.gisdata.xmlwebservices2.GetElevationResponse")
    public webservices.gov.usgs.gisdata.xmlwebservices2.GetElevationResponse.GetElevationResult getElevation(
        @WebParam(name = "X_Value", targetNamespace = "http://gisdata.usgs.gov/XMLWebServices2/")
        String xValue,
        @WebParam(name = "Y_Value", targetNamespace = "http://gisdata.usgs.gov/XMLWebServices2/")
        String yValue,
        @WebParam(name = "Elevation_Units", targetNamespace = "http://gisdata.usgs.gov/XMLWebServices2/")
        String elevationUnits,
        @WebParam(name = "Source_Layer", targetNamespace = "http://gisdata.usgs.gov/XMLWebServices2/")
        String sourceLayer,
        @WebParam(name = "Elevation_Only", targetNamespace = "http://gisdata.usgs.gov/XMLWebServices2/")
        String elevationOnly);

    /**
     * Returns values from all elevation sources for a given latitude/longitude point
     * 
     * @param elevationUnits
     * @param yValue
     * @param xValue
     * @return
     *     returns gov.usgs.gisdata.xmlwebservices2.GetAllElevationsResponse.GetAllElevationsResult
     */
    @WebMethod(action = "http://gisdata.usgs.gov/XMLWebServices2/getAllElevations")
    @WebResult(name = "getAllElevationsResult", targetNamespace = "http://gisdata.usgs.gov/XMLWebServices2/")
    @RequestWrapper(localName = "getAllElevations", targetNamespace = "http://gisdata.usgs.gov/XMLWebServices2/", className = "gov.usgs.gisdata.xmlwebservices2.GetAllElevations")
    @ResponseWrapper(localName = "getAllElevationsResponse", targetNamespace = "http://gisdata.usgs.gov/XMLWebServices2/", className = "gov.usgs.gisdata.xmlwebservices2.GetAllElevationsResponse")
    public webservices.gov.usgs.gisdata.xmlwebservices2.GetAllElevationsResponse.GetAllElevationsResult getAllElevations(
        @WebParam(name = "X_Value", targetNamespace = "http://gisdata.usgs.gov/XMLWebServices2/")
        String xValue,
        @WebParam(name = "Y_Value", targetNamespace = "http://gisdata.usgs.gov/XMLWebServices2/")
        String yValue,
        @WebParam(name = "Elevation_Units", targetNamespace = "http://gisdata.usgs.gov/XMLWebServices2/")
        String elevationUnits);

}
