
package webservices.gov.usgs.gisdata.xmlwebservices2;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * The Elevation Query Web Service returns the elevation in feet or meters for a specific latitutde/longitude (WGS 1984) point from the USGS Seamless Elevation datasets hosted at <a href="http://eros.usgs.gov/">EROS</a>.  The elevation values returned default to the best-available data source available at the specified point.  Alternately, this service may return the value from a specified data source, or from all data sources.  If unable to find data at the requested point, this service returns an extremely large, negative value (-1.79769313486231E+308).  View the detailed <a href="/XMLWebServices2/Elevation_Service_Methods.php">Elevation Service Methods</a> description for more information on the methods and parameters used in this service.  Visit <a href="http://gisdata.usgs.gov/">http://gisdata.usgs.gov/</a> to view other EROS Web Services.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "Elevation_Service", targetNamespace = "http://gisdata.usgs.gov/XMLWebServices2/", wsdlLocation = "http://gisdata.usgs.gov/XMLWebServices2/Elevation_service.asmx?WSDL")
public class ElevationService
    extends Service
{

    private final static URL ELEVATIONSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(webservices.gov.usgs.gisdata.xmlwebservices2.ElevationService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = webservices.gov.usgs.gisdata.xmlwebservices2.ElevationService.class.getResource(".");
            url = new URL(baseUrl, "http://gisdata.usgs.gov/XMLWebServices2/Elevation_service.asmx?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://gisdata.usgs.gov/XMLWebServices2/Elevation_service.asmx?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ELEVATIONSERVICE_WSDL_LOCATION = url;
    }

    public ElevationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ElevationService() {
        super(ELEVATIONSERVICE_WSDL_LOCATION, new QName("http://gisdata.usgs.gov/XMLWebServices2/", "Elevation_Service"));
    }

    /**
     * 
     * @return
     *     returns ElevationServiceSoap
     */
    @WebEndpoint(name = "Elevation_ServiceSoap")
    public ElevationServiceSoap getElevationServiceSoap() {
        return super.getPort(new QName("http://gisdata.usgs.gov/XMLWebServices2/", "Elevation_ServiceSoap"), ElevationServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ElevationServiceSoap
     */
    @WebEndpoint(name = "Elevation_ServiceSoap")
    public ElevationServiceSoap getElevationServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://gisdata.usgs.gov/XMLWebServices2/", "Elevation_ServiceSoap"), ElevationServiceSoap.class, features);
    }

}
